name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          uv pip install -e .[dev]
      - name: Run tests
        run: |
          uv run pytest
      - name: Run linter
        run: |
          uv run ruff check .

      - name: Run test coverage
        run: |
          make test-coverage
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Anik0000000_python-project-50
            -Dsonar.organization=anik0000000
            -Dsonar.python.coverage.reportPaths=coverage.xml