name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install hatch
        hatch build
        pip install ruff
        pip install dist/*.whl
        pip install pytest pytest-cov
    - name: Lint with ruff
      run: make lint
    - name: Test with pytest
      run: make test
    - name: Generate coverage
      run: make coverage
    - name: Upload coverage to SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}